name: Validate

on:
  pull_request:
  push:
    branches: [main, master]

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: juninmd/base-actions/validate-pr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
